name: check

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-check.txt

      - name: Run black
        run: |
          python -m black --check src/

      - name: Run mypy
        run: |
          python -m mypy --disallow-untyped-defs --disallow-incomplete-defs --no-implicit-optional src/

      - name: Run pydocstyle
        run: |
          python -m pydocstyle src/

      - name: Run pycodestyle
        run: |
          python -m pycodestyle src/
